// Mocks generated by Mockito 5.4.6 from annotations
// in appwizard/test/data/repositories/onboarding_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:appwizard/core/utils/app_logger.dart' as _i5;
import 'package:appwizard/features/onboarding/data/datasources/onboarding_local_datasource.dart'
    as _i2;
import 'package:appwizard/features/onboarding/data/models/onboarding_data.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OnboardingLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingLocalDataSource extends _i1.Mock
    implements _i2.OnboardingLocalDataSource {
  MockOnboardingLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveOnboardingData(_i4.OnboardingData? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveOnboardingData, [data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.OnboardingData?> getOnboardingData() =>
      (super.noSuchMethod(
            Invocation.method(#getOnboardingData, []),
            returnValue: _i3.Future<_i4.OnboardingData?>.value(),
          )
          as _i3.Future<_i4.OnboardingData?>);

  @override
  _i3.Future<void> clearOnboardingData() =>
      (super.noSuchMethod(
            Invocation.method(#clearOnboardingData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i5.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void d(String? message) => super.noSuchMethod(
    Invocation.method(#d, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void e(String? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#e, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void i(String? message) => super.noSuchMethod(
    Invocation.method(#i, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void w(String? message) => super.noSuchMethod(
    Invocation.method(#w, [message]),
    returnValueForMissingStub: null,
  );
}
